package christmas

object MessageConstants {
    const val WELCOME_MESSAGE = "안녕하세요! 우테코 식당 12월 이벤트 플래너입니다.\n" +
            "12월 중 식당 예상 방문 날짜는 언제인가요? (숫자만 입력해 주세요!)"
    const val INPUT_MENUS = "주문하실 메뉴를 메뉴와 개수를 알려 주세요. (e.g. 해산물파스타-2,레드와인-1,초코케이크-1)"
    const val ERROR_INVALID_ORDER = "[ERROR] 유효하지 않은 주문입니다. 다시 입력해 주세요."
    const val FRI = "금"
    const val SAT = "토"
    const val CHRISTMAS_DDAY_SALE = "크리스마스 디데이 할인"
    const val SPECIAL_SALE = "특별 할인"
    const val WEEKEND_SALE = "주말 할인"
    const val WEEKDAY_SALE = "평일 할인"
    const val ERROR_INVALID_DATE = "[ERROR] 유효하지 않은 날짜입니다. 다시 입력해 주세요."
    const val ERROR_JUST_ORDER_DRINK = "[ERROR] 음료만 주문하실 수 없습니다."
    const val ERROR_MORE_THAN_20_MENUS = "[ERROR] 최대 20개까지만 주문 가능합니다."
    const val SANTA = "산타"
    const val TREE = "트리"
    const val STAR = "별"
    const val EVENT_MESSAGE_START = "12월 "
    const val EVENT_MESSAGE_END = "일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!\n"
    const val ORDER_MENU = "<주문 메뉴>"
    const val UNIT = "개"
    const val TOTAL_ORDER_AMOUNT_BEFORE_DISCOUNT = "<할인 전 총주문 금액>"
    const val WON = "원"
    const val ONE_CHAMPAGNE = "샴페인 1개"
    const val NONE = "없음"
    const val GIFT_EVENT = "증정 이벤트"
    const val GIFT_MENU = "<증정 메뉴>"
    const val BENEFITS_DETAILS = "<혜택 내역>"
    const val TOTAL_BENEFIT_AMOUNT = "<총혜택 금액>"
    const val ZERO_WON = "0원"
    const val ESTIMATED_PAYMENT_AMOUNT_AFTER_DISCOUNT = "<할인 후 예상 결제 금액>"
    const val DECEMBER_EVENT_BADGE = "<12월 이벤트 배지>"
}